// AUTO-GENERATED by scripts/generate-data-files.ts
// Do not edit by hand. Re-run `npx tsx scripts/generate-data-files.ts` to regenerate.

import type { Experience } from "./types";

const experiences: Experience[] = [
  {
    id: 10,
    title: "비상교육",
    period: "2024 - 현재",
    items: [
      "React, Typescript 기반의 Micro Frontend Service 개발 및 유지보수",
      "소켓 통신의 양방향 수업 플랫폼 개발 및 유지보수",
      "레거시 코드 개선 및 리팩토링(Webpack, React 버전 업그레이드, 상태 관리 store 도메인 기준 분리, 중복 코드 제거 및 모듈화 등)",
    ],
    links: [],
    is_active: true,
    sub_title: "글로벌 Company, 소프트웨어개발 Cell",
    index: 1,
    skill_ids: [1, 2, 5, 6, 12, 16],
    category: "WORK",
  },
  {
    id: 2,
    title: "코드스테이츠",
    period: "2022 - 2023",
    items: [
      "회사 홈페이지, 교육 관리 시스템(LMS) 개발 및 유지보수 (React.js, Next.js, Typescript 기반)",
      "어드민 시스템 MVP 모델 개발, ver.2까지 제품 고도화 (React.js, Typescript 기반)",
      "블로그 개발 및 검색엔진 최적화 작업 (유입트래픽 25.6% 상승)",
      "성능 최적화 TF, 디자인 시스템 TF 참여",
      "통합 로그인 시스템 개발, 제품 간 통합 로그인 상태관리 구현",
    ],
    links: [
      {
        label: "웹사이트",
        href: "https://www.codestates.com/",
      },
      {
        label: "코드스테이츠 블로그",
        href: "https://www.codestates.com/blog",
      },
    ],
    is_active: false,
    sub_title: "IT 교육 부트캠프 스타트업<br/>Internal System Product팀, Frontend-Engineer",
    index: 2,
    skill_ids: [1, 5, 6, 7, 8, 9, 11, 12, 15, 18, 19, 20, 21],
    category: "WORK",
  },
  {
    id: 1,
    title: "티끌",
    period: "2023 - 2024",
    items: [
      "React, TypeScript 기반의 SPA 개발. 모바일 / 데스크탑 대응 반응형 웹사이트 개발",
      "Redux 이용하여 클라이언트 상태 관리, React-Query 이용하여 서버 상태 관리 구현",
      "React-hook-form 활용하여 form 상태 관리 및 validation 구현",
      "Figma 활용 유저 스토리 및 와이어프레임 작성, UI/UX 디자인",
    ],
    links: [
      {
        label: "Figma",
        href: "https://www.figma.com/file/ak0eHSwx6SW3cYfR9MdPmG/High-Fidelity?type=design&node-id=197-138&mode=design",
      },
      {
        label: "Github",
        href: "https://github.com/kdh-92/Tiggle",
      },
    ],
    is_active: false,
    sub_title: "가계부 공유 플랫폼 개발 프로젝트",
    index: 3,
    skill_ids: [1, 5, 9, 10, 8, 12, 14, 17, 27],
    category: "PROJECT",
  },
  {
    id: 3,
    title: "Touch Art Archive",
    period: "2021.11 - 12",
    items: [
      "React, JavaScript(ES6) 기반의 SPA 개발. Carousel UI 구현",
      "Redux 이용하여 클라이언트 언어 상태 관리, 다언어 기능 구현",
      "기초적인 검색엔진최적화 작업",
    ],
    links: [
      {
        label: "웹사이트",
        href: "http://touchartarchive.com/",
      },
      {
        label: "소개 영상",
        href: "https://youtu.be/o4dXz-8OKkk",
      },
    ],
    is_active: false,
    sub_title: "맹학교 미술 수업용 회화 작품 3D 프린팅 파일 아카이빙 프로젝트",
    index: 4,
    skill_ids: [1, 5, 10, 22],
    category: "PROJECT",
  },
  {
    id: 5,
    title: "Art&Technology Conference 2020",
    period: "2020 - 2021",
    items: [
      "React, JavaScript(ES6) 이용하여 SPA Web 개발",
      "가로 스크롤 페이지 구현. 세로 스크롤을 가로로 변환하는 React hook 작성",
      "Google Apps Script 이용하여 spread sheet를 DB로 활용, 콘텐츠 페이지 어드민 기능과 방명록 기능 구현",
      "AWS S3와 Route 53 이용하여 배포, 사용자 로그 수집 후 분석하여 고유 방문자 수 계산 (1개월 간 고유 방문자수 3,500명 달성)",
    ],
    links: [
      {
        label: "웹사이트",
        href: "https://www.atcbackup.meganmagic.com/",
      },
      {
        label: "Github",
        href: "https://github.com/MeganMagic/atc2020-refac-1",
      },
    ],
    is_active: false,
    sub_title: "서강대학교 Art&Technology 전공의 연간 학생 전시",
    index: 5,
    skill_ids: [1, 6],
    category: "PROJECT",
  },
  {
    id: 4,
    title: "스탠다드 로봇",
    period: "2021.09 - 11",
    items: [
      "Adobe XD 이용하여 반응형 웹사이트 UI/UX 디자인",
      "React, JavaScript(ES6) 이용하여 웹 프론트엔드 개발",
      "이메일 문의하기 기능 구현",
    ],
    links: [],
    is_active: false,
    sub_title: "홈페이지 제작 외주<br/>UI/UX 디자이너 및 Frontend 개발자",
    index: 6,
    skill_ids: [1, 6, 3],
    category: "WORK",
  },
];

export default experiences;
