/**
 * Shared data types for static portfolio content.
 *
 * These types mirror what was previously generated by Prisma. They are kept
 * loose-but-precise on purpose so that the same structures used to live in the
 * Postgres database can be expressed as plain TypeScript modules.
 */

export type Category = "FRONTEND" | "FRONTEND_LIBRARY" | "ENV" | "DESIGN" | "ETC";

export interface Skill {
  id: number;
  category: Category;
  items: string[];
  item: string;
  blobUrl: string;
}

export interface Intro {
  id: number;
  title: string;
  detail: string;
  blobUrl: string | null;
}

export interface Blog {
  id: number;
  title: string;
  date: string;
  forwardLink: string;
  bgImageUrl: string;
}

export interface ExperienceLink {
  label: string;
  href: string;
}

export interface Experience {
  id: number;
  title: string;
  period: string;
  items: string[];
  links: ExperienceLink[];
  is_active: boolean | null;
  sub_title: string | null;
  index: number;
  skill_ids: number[];
  category: string | null;
}

// A curated project case, shown as an inline accordion (problem → approach → result).
export interface ProjectCase {
  id: string;
  company: string;
  period: string;
  title: string;
  summary: string;
  points: string[];
  stack: string[];
  links?: ExperienceLink[];
}

export interface Education {
  id: number;
  title: string;
  sub_title: string;
  period: string;
  items: string[];
  category: string | null;
}
