/**
 * Shared data types for static portfolio content.
 *
 * These types mirror what was previously generated by Prisma. They are kept
 * loose-but-precise on purpose so that the same structures used to live in the
 * Postgres database can be expressed as plain TypeScript modules.
 */

export type Category = "FRONTEND" | "FRONTEND_LIBRARY" | "ENV" | "DESIGN" | "ETC";
export type Ratio = "PORTRAIT" | "LANDSCAPE" | "SQUARE";

export interface Skill {
  id: number;
  category: Category;
  items: string[];
  item: string;
  blobUrl: string;
}

export interface Intro {
  id: number;
  title: string;
  detail: string;
  blobUrl: string | null;
}

export interface Blog {
  id: number;
  title: string;
  date: string;
  forwardLink: string;
  bgImageUrl: string;
}

export interface ExperienceLink {
  label: string;
  href: string;
}

export interface Experience {
  id: number;
  title: string;
  period: string;
  items: string[];
  links: ExperienceLink[];
  is_active: boolean | null;
  sub_title: string | null;
  index: number;
  skill_ids: number[];
  category: string | null;
}

export interface ProjectItem {
  id: number;
  title: string;
  content: string[];
  projectId: number | null;
  blobUrl: string | null;
  row_number: number | null;
  image_ratio: Ratio | null;
}

export interface Project {
  id: number;
  title: string;
  sub_title: string;
  period: string;
  member: string;
  skills: string[];
  links: ExperienceLink[];
  skill_ids: number[];
  row_number: number | null;
  items: ProjectItem[];
}

export interface Education {
  id: number;
  title: string;
  sub_title: string;
  period: string;
  items: string[];
  category: string | null;
}
